import React, { useState } from 'react';
import { X, Download, Copy, Check, FileText, Share2 } from 'lucide-react';
import { Notebook, ResearchSource, ChatMessage, StudioSavedItem } from '../../types';

interface ShareExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  notebook: Notebook;
  sources: ResearchSource[];
  messages: ChatMessage[];
  savedItems: StudioSavedItem[];
}

export const ShareExportModal: React.FC<ShareExportModalProps> = ({
  isOpen,
  onClose,
  notebook,
  sources,
  messages,
  savedItems,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownReport = () => {
    let md = `# Research Dossier: ${notebook.title}\n\n`;
    md += `*Generated by Loomind Noesis Research Workspace*\n`;
    md += `*Date: ${new Date().toLocaleDateString()}*\n\n`;
    md += `## Abstract / Scope\n${notebook.description}\n\n`;

    md += `## Attached Literature & Sources (${sources.length})\n`;
    sources.forEach((s) => {
      md += `### [${s.citationIndex}] ${s.title}\n`;
      md += `- **Type**: ${s.type}\n`;
      if (s.author) md += `- **Author**: ${s.author} (${s.publishedYear || 'N/A'})\n`;
      md += `- **Word Count**: ${s.wordCount}\n\n`;
    });

    if (savedItems.length > 0) {
      md += `## Saved Studio Artifacts (${savedItems.length})\n`;
      savedItems.forEach((item) => {
        md += `### ${item.title} (${item.toolType})\n`;
        md += `\`\`\`json\n${JSON.stringify(item.data, null, 2)}\n\`\`\`\n\n`;
      });
    }

    if (messages.length > 0) {
      md += `## Synthesis Q&A Transcripts\n`;
      messages.forEach((m) => {
        md += `**${m.role.toUpperCase()}** (${new Date(m.timestamp).toLocaleTimeString()}):\n${m.content}\n\n`;
      });
    }

    return md;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownReport();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${notebook.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-research-report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJson = () => {
    const data = {
      notebook,
      sources,
      messages,
      savedItems,
      exportedAt: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${notebook.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-workspace-export.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in duration-150">
      <div className="bg-white dark:bg-slate-900 rounded-2xl max-w-lg w-full border border-slate-200 dark:border-slate-800 shadow-2xl overflow-hidden flex flex-col">
        {/* Header */}
        <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Share2 className="w-4 h-4 text-indigo-500" />
            <h3 className="text-sm font-bold text-slate-900 dark:text-white">
              Export Research Dossier
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="p-5 space-y-4 text-xs">
          <p className="text-slate-600 dark:text-slate-300">
            Export all grounded evidence, conversation transcripts, citations, and studio study artifacts for <strong>{notebook.title}</strong>:
          </p>

          <div className="space-y-2">
            <button
              onClick={handleCopyMarkdown}
              className="w-full p-3 bg-slate-50 dark:bg-slate-800/80 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-left flex items-center justify-between transition-colors cursor-pointer"
            >
              <div className="flex items-center gap-2.5">
                <Copy className="w-4 h-4 text-indigo-500" />
                <div>
                  <p className="font-bold text-slate-900 dark:text-white">Copy Markdown Report</p>
                  <p className="text-[11px] text-slate-400">Formatted dossier for notes apps</p>
                </div>
              </div>
              {copied ? (
                <span className="text-emerald-500 font-bold flex items-center gap-1">
                  <Check className="w-4 h-4" />
                </span>
              ) : (
                <span className="text-slate-400 text-xs">Copy</span>
              )}
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="w-full p-3 bg-slate-50 dark:bg-slate-800/80 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-left flex items-center justify-between transition-colors cursor-pointer"
            >
              <div className="flex items-center gap-2.5">
                <Download className="w-4 h-4 text-emerald-500" />
                <div>
                  <p className="font-bold text-slate-900 dark:text-white">Download Markdown (.md)</p>
                  <p className="text-[11px] text-slate-400">Complete structured research report file</p>
                </div>
              </div>
              <span className="text-slate-400 text-xs">.md</span>
            </button>

            <button
              onClick={handleDownloadJson}
              className="w-full p-3 bg-slate-50 dark:bg-slate-800/80 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-left flex items-center justify-between transition-colors cursor-pointer"
            >
              <div className="flex items-center gap-2.5">
                <FileText className="w-4 h-4 text-amber-500" />
                <div>
                  <p className="font-bold text-slate-900 dark:text-white">Download Full Workspace (.json)</p>
                  <p className="text-[11px] text-slate-400">Portable JSON bundle with full state</p>
                </div>
              </div>
              <span className="text-slate-400 text-xs">.json</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
